apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
   # syncOptions:
   #   - CreateNamespace=true

  sources:
    # repo بتاع values
    - repoURL: https://github.com/habdelazim743-collab/complete_k8s_config_for_netfix_app
      targetRevision: main
      ref: values

    # Prometheus + Grafana + Alertmanager
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 58.6.0
      helm:
        valueFiles:
          - $values/monitoring/prometheus/values.yaml

    # Elasticsearch
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.12.0
      helm:
        valueFiles:
          - $values/monitoring/elk/elasticsearch-values.yaml

    # Kibana
    - repoURL: https://helm.elastic.co
      chart: kibana
      targetRevision: 8.12.0
      helm:
        valueFiles:
          - $values/monitoring/elk/kibana-values.yaml

    # Filebeat
    - repoURL: https://helm.elastic.co
      chart: filebeat
      targetRevision: 8.12.0
      helm:
        valueFiles:
          - $values/monitoring/elk/filebeat-values.yaml

