apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: auth
type: Opaque
data:
  OAUTH2_PROXY_CLIENT_ID: b2F1dGgyLXByb3h5
  OAUTH2_PROXY_CLIENT_SECRET: U1VISzVCMlc0ZklxamtQMk15eHZqWFMyRmk1WEdxbnc=
  OAUTH2_PROXY_COOKIE_SECRET: bXRxM0FrYlBkRzUzSlhBeDdEeVRLRzRlNTlhWGtYdHZTYnhUejRGQ2JVQT0=

