apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netfix-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/habdelazim743-collab/complete_k8s_config_for_netfix_app
    targetRevision: main
    path: root
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      #prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

