apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db
  namespace: auth
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore

  target:
    name: keycloak-db
    creationPolicy: Owner

  data:
    - secretKey: KC_DB
      remoteRef:
        key: keycloak-db  # ← No prefix
        property: engine

    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: keycloak-db  # ← No prefix
        property: username

    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: keycloak-db  # ← No prefix
        property: password

    - secretKey: KC_DB_URL
      remoteRef:
        key: keycloak-db  # ← No prefix
        property: jdbcConnectionString
