apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: auth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  
  target:
    name: keycloak-admin
    creationPolicy: Owner
  
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: netflix/keycloak/admin
        property: username
    
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: netflix/keycloak/admin
        property: password
